"""Direct Python SDK for Chrome Bridge."""

from .client import ChromeBridge, ChromeBridgeSession, SessionStatus, StatusCallback
from .errors import (
    ChromeBridgeError,
    ExtensionUnavailableError,
    IncompatibleServerError,
    NestedSessionError,
    OperationError,
    OperationOutcomeUnknownError,
    ServerUnavailableError,
    SessionAcquireTimeoutError,
    SessionExpiredError,
)
from .models import (
    BrowserInstance,
    ClosedTab,
    ConsoleEntry,
    Download,
    DownloadFileResult,
    KeyPress,
    RecordedResult,
    Recording,
    Screenshot,
    Snapshot,
    Tab,
    WaitResult,
)

__all__ = [
    "ChromeBridge",
    "ChromeBridgeError",
    "ChromeBridgeSession",
    "BrowserInstance",
    "ClosedTab",
    "ConsoleEntry",
    "Download",
    "DownloadFileResult",
    "ExtensionUnavailableError",
    "IncompatibleServerError",
    "KeyPress",
    "NestedSessionError",
    "OperationError",
    "OperationOutcomeUnknownError",
    "RecordedResult",
    "Recording",
    "Screenshot",
    "ServerUnavailableError",
    "SessionAcquireTimeoutError",
    "SessionExpiredError",
    "SessionStatus",
    "Snapshot",
    "StatusCallback",
    "Tab",
    "WaitResult",
]
